/// Usuarios
List<Map<String, dynamic>> usuarios = [
  {
    'idusuario': 'u1',
    'nombre': 'Juan',
    'apellido': 'Pérez',
    'email': 'juan@mail.com',
    'contra': '123456',
    'fechanaci': '2000-01-01',
  },
  {
    'idusuario': 'u2',
    'nombre': 'Ana',
    'apellido': 'García',
    'email': 'ana@mail.com',
    'contra': 'abcdef',
    'fechanaci': '1998-05-12',
  },
];

List<Map<String, dynamic>> peliculas = [
  // TERROR
  {
    'idpelicula': 1,
    'Titulo': 'El Conjuro',
    'Genero': 'Terror',
    'Sinopsis': 'Una familia enfrenta fenómenos paranormales tras mudarse a una granja. Los investigadores Ed y Lorraine Warren intentan ayudarlos antes de que sea demasiado tarde.',
    'img_url': 'https://m.media-amazon.com/images/M/MV5BYWQyNTQwNTAtZDE2Yy00NjlhLWE4N2YtYjBkYTM4ZmM3ZDk0XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
    'Elenco': ['Vera Farmiga', 'Patrick Wilson', 'Lili Taylor', 'Ron Livingston'],
    'Director': 'James Wan',
    'calificaciones': <int>[],
    'favoritos': <String>[],
    'deseados' : <String>[],
    'img_url2' : 'https://www.pointgraf.com.uy/trabajos/web/web4/img/elConjuro.jpg',
  },
  {
    'idpelicula': 2,
    'Titulo': 'Actividad Paranormal',
    'Genero': 'Terror',
    'Sinopsis': 'Una pareja instala cámaras para captar extraños sucesos en casa. Lo que graban revela presencias malignas que amenazan con descontrolarse.',
    'img_url': 'https://m.media-amazon.com/images/M/MV5BZmZhYTk2MzQtMmIwMi00ODk5LWIzNWEtYzIwYmQ5ZDA3YzNjXkEyXkFqcGc@._V1_.jpg',
    'Elenco': ['Katie Featherston', 'Micah Sloat', 'Mark Fredrichs', 'Amber Armstrong'],
    'Director': 'Oren Peli',
    'calificaciones': <int>[],
    'favoritos': <String>[],
    'deseados' : <String>[],
    'img_url2' : 'https://img.asmedia.epimg.net/resizer/v2/VBPWVXZSDVOO5O25ADD6QZKW3Q.jpg?auth=56869d02a757cc5480dbbc48578c2e1804bf6c355d0a7482615c49475dec8d2e&width=1472&height=828&smart=true',
  },
  {
    'idpelicula': 3,
    'Titulo': 'La Monja',
    'Genero': 'Terror',
    'Sinopsis': 'Un sacerdote y una novicia investigan la muerte de una monja en Rumania. Enfrentan una fuerza demoníaca que amenaza su fe y vidas.',
    'img_url': 'https://m.media-amazon.com/images/M/MV5BZjE0ZjIwZDYtN2UyNi00YTEzLWJlZjAtNWQxYjk5OWE1YjJiXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
    'Elenco': ['Demián Bichir', 'Taissa Farmiga', 'Jonas Bloquet', 'Bonnie Aarons'],
    'Director': 'Corin Hardy',
    'calificaciones': <int>[],
    'favoritos': <String>[],
    'deseados' : <String>[],
    'img_url2' : 'https://elcomercio.pe/resizer/-ssvbyLYL_CXFhosyI2JiwHYDuk=/1214x697/smart/filters:format(jpeg):quality(75)/arc-anglerfish-arc2-prod-elcomercio.s3.amazonaws.com/public/O4LO44XPCBHCLKASFTKIFNL454.jpg',
  },
  {
    'idpelicula': 4,
    'Titulo': 'It (Eso)',
    'Genero': 'Terror',
    'Sinopsis': 'Un grupo de niños se enfrenta a una entidad maligna que adopta la forma de un payaso para sembrar terror en su pueblo.',
    'img_url': 'https://m.media-amazon.com/images/M/MV5BZDFhODExOTctNTFkZS00NjE1LWE2MWMtY2Q1ZThhMGY5NjJkXkEyXkFqcGc@._V1_.jpg',
    'Elenco': ['Bill Skarsgård', 'Jaeden Martell', 'Finn Wolfhard', 'Sophia Lillis'],
    'Director': 'Andy Muschietti',
    'calificaciones': <int>[],
    'favoritos': <String>[],
    'deseados' : <String>[],
    'img_url2' : 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSy4MiHBxhsWROdOc_zB0H5fqXsB6ibmXoYug&s',
  },
  {
    'idpelicula': 5,
    'Titulo': 'Insidious',
    'Genero': 'Terror',
    'Sinopsis': 'Una familia lucha contra espíritus que intentan poseer a su hijo, atrapado en un mundo espiritual conocido como El Más Allá.',
    'img_url': 'https://m.media-amazon.com/images/M/MV5BMTYyOTAxMDA0OF5BMl5BanBnXkFtZTcwNzgwNTc1NA@@._V1_.jpg',
    'Elenco': ['Patrick Wilson', 'Rose Byrne', 'Ty Simpkins', 'Lin Shaye'],
    'Director': 'James Wan',
    'calificaciones': <int>[],
    'favoritos': <String>[],
    'deseados' : <String>[],
    'img_url2' : 'https://wallpapers.com/images/hd/insidious-dalton-poster-oxc8bz0d41bhgrd5.jpg',
  },

  // COMEDIA
  {
    'idpelicula': 6,
    'Titulo': '¿Qué pasó ayer?',
    'Genero': 'Comedia',
    'Sinopsis': 'Tres amigos pierden al novio durante una despedida de soltero en Las Vegas y deben reconstruir los hechos para encontrarlo a tiempo.',
    'img_url': 'https://m.media-amazon.com/images/M/MV5BOWY0YzE1OTYtOTZkZC00YTVhLTkwZjQtYTQwNmExNmUxYTU4XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
    'Elenco': ['Bradley Cooper', 'Zach Galifianakis', 'Ed Helms', 'Justin Bartha'],
    'Director': 'Todd Phillips',
    'calificaciones': <int>[],
    'favoritos': <String>[],
    'deseados' : <String>[],
    'img_url2' : 'https://m.media-amazon.com/images/S/pv-target-images/9e0ba02666349b16571bbf4ff835f15180e0aa6f95d02802edda1a94d1ba8dc6.jpg',
  },
  {
    'idpelicula': 7,
    'Titulo': 'Superbad',
    'Genero': 'Comedia',
    'Sinopsis': 'Dos adolescentes planean disfrutar su última fiesta antes de graduarse, enfrentando una serie de situaciones cómicas e inesperadas.',
    'img_url': 'https://m.media-amazon.com/images/I/81fqqQrgyqL._UF894,1000_QL80_.jpg',
    'Elenco': ['Jonah Hill', 'Michael Cera', 'Christopher Mintz-Plasse', 'Emma Stone'],
    'Director': 'Greg Mottola',
    'calificaciones': <int>[],
    'favoritos': <String>[],
    'deseados' : <String>[],
    'img_url2' : 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRwsbDzLbjTNldH_a9lTW1qZ_ZrkdVfd-Sung&s',
  },
  {
    'idpelicula': 8,
    'Titulo': 'Legalmente Rubia',
    'Genero': 'Comedia',
    'Sinopsis': 'Una joven rubia entra a la facultad de derecho de Harvard para recuperar a su ex, pero descubre su verdadera vocación y poder.',
    'img_url': 'https://m.media-amazon.com/images/M/MV5BZTcwNzYzNTYtOGE3NS00ODViLTg1ZDAtNjY1M2QxMGM1NTk3XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
    'Elenco': ['Reese Witherspoon', 'Luke Wilson', 'Selma Blair', 'Jennifer Coolidge'],
    'Director': 'Robert Luketic',
    'calificaciones': <int>[],
    'favoritos': <String>[],
    'deseados' : <String>[],
    'img_url2' : 'https://www.diarioconstitucional.cl/wp-content/uploads/2023/01/Sin-titulo-33.jpg',
  },
  {
    'idpelicula': 9,
    'Titulo': 'Loco por Mary',
    'Genero': 'Comedia',
    'Sinopsis': 'Un hombre contrata a un detective para reencontrarse con su amor de juventud, pero la situación se complica con múltiples pretendientes.',
    'img_url': 'https://m.media-amazon.com/images/M/MV5BNmZmNjRkNzAtMzZlZC00MGI4LWJhZmYtZDM2MDdlODMxMDU5XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
    'Elenco': ['Cameron Diaz', 'Ben Stiller', 'Matt Dillon', 'Chris Elliott'],
    'Director': 'Bobby Farrelly, Peter Farrelly',
    'calificaciones': <int>[],
    'favoritos': <String>[],
    'deseados' : <String>[],
    'img_url2' : 'https://image.tmdb.org/t/p/original/egJQ3nIon5fT8wyXcKRHzvmtZpD.jpg',
  },

  {
    'idpelicula': 10,
    'Titulo': 'Mi Pobre Angelito',
    'Genero': 'Comedia',
    'Sinopsis': 'Un niño se queda solo en casa y debe defenderla de dos torpes ladrones con ingeniosas trampas durante las fiestas navideñas.',
    'img_url': 'https://m.media-amazon.com/images/M/MV5BZWU2NTc5OTUtYzU2NS00Yzk0LWI1MWItMTMxOGZhOTJiMjM0XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
    'Elenco': ['Macaulay Culkin', 'Joe Pesci', 'Daniel Stern', 'Catherine O’Hara'],
    'Director': 'Chris Columbus',
    'calificaciones': <int>[],
    'favoritos': <String>[],
    'deseados' : <String>[],
    'img_url2' : 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRVnFFZNLOCQUWnLLJCS0IoVT8w5DeXAtNN4A&s',
  },

  // ANIMADOS
  {
    'idpelicula': 11,
    'Titulo': 'Coco',
    'Genero': 'Animados',
    'Sinopsis': 'Un niño músico viaja accidentalmente al mundo de los muertos en el Día de los Muertos y descubre la historia de su familia.',
    'img_url': 'https://lumiere-a.akamaihd.net/v1/images/p_coco_19736_fd5fa537.jpeg?region=0%2C0%2C540%2C810',
    'Elenco': ['Anthony Gonzalez', 'Gael García Bernal', 'Benjamin Bratt', 'Alanna Ubach'],
    'Director': 'Lee Unkrich',
    'calificaciones': <int>[],
    'favoritos': <String>[],
    'deseados' : <String>[],
    'img_url2' : 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRyPKEKpVsd-kvp3W595K8fM5nLnTiKRsO8zA&s',
  },
  {
    'idpelicula': 12,
    'Titulo': 'Intensamente',
    'Genero': 'Animados',
    'Sinopsis': 'Las emociones dentro de la mente de una niña enfrentan desafíos cuando su vida cambia por una mudanza. Aprenden a trabajar juntas.',
    'img_url': 'https://m.media-amazon.com/images/S/pv-target-images/7a1a086a63906a1449f4a7a19b98513c66099c146cc9de0480e08c1a1364d097.jpg',
    'Elenco': ['Amy Poehler', 'Phyllis Smith', 'Bill Hader', 'Mindy Kaling'],
    'Director': 'Pete Docter',
    'calificaciones': <int>[],
    'favoritos': <String>[],
    'deseados' : <String>[],
    'img_url2' : 'https://menos1cine.cl/wp-content/uploads/2024/05/inside-out-1.jpg',
  },
  {
    'idpelicula': 13,
    'Titulo': 'Shrek',
    'Genero': 'Animados',
    'Sinopsis': 'Un ogro solitario emprende una misión para rescatar a una princesa, descubriendo la importancia del amor, la amistad y la aceptación.',
    'img_url': 'https://m.media-amazon.com/images/S/pv-target-images/030f9ae65cadc9afc0e3c51ed35d2ddeb814f213d7a87fc5aa4445738ebb32b9.jpg',
    'Elenco': ['Mike Myers', 'Eddie Murphy', 'Cameron Diaz', 'John Lithgow'],
    'Director': 'Andrew Adamson, Vicky Jenson',
    'calificaciones': <int>[],
    'favoritos': <String>[],
    'deseados' : <String>[],
    'img_url2' : 'https://pbs.twimg.com/media/E0FzrFWVgAEI3i6.jpg',
  },
  {
    'idpelicula': 14,
    'Titulo': 'Zootopia',
    'Genero': 'Animados',
    'Sinopsis': 'Una coneja policía y un zorro estafador trabajan juntos para resolver una conspiración en una ciudad donde todos los animales conviven.',
    'img_url': 'https://m.media-amazon.com/images/M/MV5BOTMyMjEyNzIzMV5BMl5BanBnXkFtZTgwNzIyNjU0NzE@._V1_.jpg',
    'Elenco': ['Ginnifer Goodwin', 'Jason Bateman', 'Idris Elba', 'Jenny Slate'],
    'Director': 'Byron Howard, Rich Moore',
    'calificaciones': <int>[],
    'favoritos': <String>[],
    'deseados' : <String>[],
    'img_url2' : 'https://wallpapers.com/images/featured/imagenes-de-zootopia-e8u4m9lttr2wlg4q.jpg',
  },
  {
    'idpelicula': 15,
    'Titulo': 'Ratatouille',
    'Genero': 'Animados',
    'Sinopsis': 'Un ratón con talento culinario forma una inesperada alianza con un joven cocinero para alcanzar su sueño de ser chef en París.',
    'img_url': 'https://m.media-amazon.com/images/I/81n+81eQRuL._UF894,1000_QL80_.jpg',
    'Elenco': ['Patton Oswalt', 'Lou Romano', 'Peter Sohn', 'Ian Holm'],
    'Director': 'Brad Bird',
    'calificaciones': <int>[],
    'favoritos': <String>[],
    'deseados' : <String>[],
    'img_url2' : 'https://miro.medium.com/v2/resize:fit:1200/1*ImvnPCERNvEguOBWLbSVig.jpeg',
  },

  // SUSPENSO
  {
    'idpelicula': 16,
    'Titulo': 'Perdida',
    'Genero': 'Suspenso',
    'Sinopsis': 'Un esposo se convierte en sospechoso cuando su esposa desaparece misteriosamente, mientras oscuros secretos salen a la luz.',
    'img_url': 'https://m.media-amazon.com/images/M/MV5BNjMyYzA2MDAtZGRiMS00NWRhLThjN2ItMmYwNjdiMzRmNjc0XkEyXkFqcGc@._V1_.jpg',
    'Elenco': ['Ben Affleck', 'Rosamund Pike', 'Neil Patrick Harris', 'Tyler Perry'],
    'Director': 'David Fincher',
    'calificaciones': <int>[],
    'favoritos': <String>[],
    'deseados' : <String>[],
    'img_url2' : 'https://carinena.es/wp-content/uploads/2018/09/Perdida_Poster.jpg',
  },
  {
    'idpelicula': 17,
    'Titulo': 'Fragmentado',
    'Genero': 'Suspenso',
    'Sinopsis': 'Un hombre con múltiples personalidades secuestra a tres chicas. Las jóvenes intentan escapar mientras descubren su lado más peligroso.',
    'img_url': 'https://m.media-amazon.com/images/M/MV5BMmViYzcyNzItNGNlOC00YmZjLWJlYWUtZjY4Mjc2OTQxNGUzXkEyXkFqcGc@._V1_.jpg',
    'Elenco': ['James McAvoy', 'Anya Taylor-Joy', 'Betty Buckley', 'Haley Lu Richardson'],
    'Director': 'M. Night Shyamalan',
    'calificaciones': <int>[],
    'favoritos': <String>[],
    'deseados' : <String>[],
    'img_url2' : 'https://i0.wp.com/trestristescriticos.com/wp-content/uploads/2017/05/fragmentado.jpg?fit=1024%2C768&ssl=1',
  },
  {
    'idpelicula': 18,
    'Titulo': 'La Chica del Tren',
    'Genero': 'Suspenso',
    'Sinopsis': 'Una mujer observa a una pareja desde el tren, pero un día presencia algo inquietante que la involucra en una investigación criminal.',
    'img_url': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ4pQAyoY8GAHL13cHKJYskF5aIM1XLzlFhRQ&s',
    'Elenco': ['Emily Blunt', 'Haley Bennett', 'Rebecca Ferguson', 'Justin Theroux'],
    'Director': 'Tate Taylor',
    'calificaciones': <int>[],
    'favoritos': <String>[],
    'deseados' : <String>[],
    'img_url2' : '',
  },
  {
    'idpelicula': 19,
    'Titulo': 'El Cisne Negro',
    'Genero': 'Suspenso',
    'Sinopsis': 'Una bailarina lucha por conseguir el papel principal en "El lago de los cisnes", enfrentando presión psicológica y oscuras obsesiones.',
    'img_url': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQlnoQbrpjKcBEv8dvqBJdBmSnEpfx4BUhEtw&s',
    'Elenco': ['Natalie Portman', 'Mila Kunis', 'Vincent Cassel', 'Barbara Hershey'],
    'Director': 'Darren Aronofsky',
    'calificaciones': <int>[],
    'favoritos': <String>[],
    'deseados' : <String>[],
    'img_url2' : 'https://i0.wp.com/www.love4musicals.com/wp-content/uploads/2022/10/chi.jpg?fit=1280%2C720&ssl=1',
  },
  {
    'idpelicula': 20,
    'Titulo': 'Escape Room',
    'Genero': 'Suspenso',
    'Sinopsis': 'Seis extraños participan en un juego de escape por un gran premio, pero pronto descubren que sus vidas corren verdadero peligro.',
    'img_url': 'https://m.media-amazon.com/images/M/MV5BMjQ2NDMwMTY3MF5BMl5BanBnXkFtZTgwNDg5OTc1NjM@._V1_FMjpg_UX1000_.jpg',
    'Elenco': ['Taylor Russell', 'Logan Miller', 'Deborah Ann Woll', 'Jay Ellis'],
    'Director': 'Adam Robitel',
    'calificaciones': <int>[],
    'favoritos': <String>[],
    'deseados' : <String>[],
    'img_url2' : 'https://is1-ssl.mzstatic.com/image/thumb/Video123/v4/00/bf/78/00bf7851-2679-69da-3f80-a8ad4d552015/contsched.ugeaukku.png/1200x675.jpg',
  },
];


List<Map<String, dynamic>> calificaciones = [];
